# Generated by Django 3.2.6 on 2021-08-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_auto_20210805_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='valor_minino',
            new_name='valor_minimo',
        ),
    ]
